services:
    Doctrine\ORM\EntityManager:
        class: Doctrine\ORM\EntityManager
        public: true
        factory: ['Doctrine\ORM\EntityManager', 'create']
        arguments:
            - '@doctrine.dbal.default_connection'
            - '@doctrine.orm.default_configuration'
