framework:
    validation:
        email_validation_mode: html5
        enable_annotations: true

        auto_mapping:
            App\Model\Entity\: []

when@test:
    framework:
        validation:
            not_compromised_password: false
            enable_annotations: true
